### ISSUE TITLE
vscan-windows  exe  运行不了是怎么回事

### ISSUE THREAD

**Issue by toor123Himmel66** [veo/vscan#21]
谢谢

**Comment by veo** [comment]
感谢提交issues
windows需要使用-no-color参数去除色彩才会正常显示结果，后续会添加默认windows不使用色彩的代码

**Comment by veo** [comment]
另外测试过程中也发现可能是默认速率过快的原因，扫描单个目标有可能没有结果。也会在后续代码中修复
