### ISSUE TITLE
优化进行中，-l 指定url清单，扫描过程中丢弃路径去检测，出现大量404的问题

### ISSUE THREAD

**Issue by hktalent** [veo/vscan#22]
优化进行中，-l 指定url清单，扫描过程中丢弃路径去检测，出现大量404的问题
当前的流程是依赖
naabu -> httpx->vscan检测，
导致传入参数丢失url路径信息，最终大量检测都是404，缺失web上下文

**Comment by NSObjects** [comment]
缺失

**Comment by hktalent** [comment]
> 缺失

thanks

**Comment by hktalent** [comment]
修复于http://github.com/hktalent/vscan分支，增加参数-up
