### ISSUE TITLE
arm64-vscan

### ISSUE THREAD

**Issue by acz132** [veo/vscan#24]
麻烦帮忙编译一下arm64的vscan

**Comment by veo** [comment]
> 

感谢提交建议，下个版本会加入arm版的文件

如需现版本arm文件，可以clone 源码自行编译

**Comment by acz132** [comment]
麻烦帮忙编译一下

**Comment by veo** [comment]
> 麻烦帮忙编译一下

我尽力了，我的机器是amd64的，试了用docker交叉编译，libpcap编译不了。

你找台arm64的机器或者虚拟机编译就行，我手上没有
