### ISSUE TITLE
指纹识别小优化

### ISSUE THREAD

**Issue by yhy0** [veo/vscan#26]
pkg/fingerprint/matchfinger.go 中的 iskeyword 函数 应该改为不区分大小写检测比较好
`strings.Contains(strings.ToLower(str), strings.ToLower(k)) `

emobile 指纹都没有识别到，原因就是  window.apiPrifix 与指纹 window.apiprifix 没有匹配到

**Comment by veo** [comment]
> pkg/fingerprint/matchfinger.go 中的 iskeyword 函数 应该改为不区分大小写检测比较好 `strings.Contains(strings.ToLower(str), strings.ToLower(k)) `
> 
> emobile 指纹都没有识别到，原因就是 window.apiPrifix 与指纹 window.apiprifix 没有匹配到

感谢提交建议，我马上解决这个问题
