### ISSUE TITLE
Go Compilation Error

### ISSUE THREAD

**Issue by qusaialhaddad** [veo/vscan#27]
Hi I am getting this error while compiling the package 

# github.com/google/gopacket/pcap
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by veo** [comment]
Read https://github.com/veo/vscan/blob/main/static/Installation.md

you should install libpcap first
