### ISSUE TITLE
build command-line-arguments: cannot load embed: malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by 4riful** [veo/vscan#28]
i run sudo go run main.go -host 127.0.01/24 -top-ports top-100

this and encounterd with this err

![image](https://user-images.githubusercontent.com/45453772/175291428-eed6599f-9b3a-4813-b1e9-09decddbf803.png)

**Comment by 4riful** [comment]
could you fix it

**Comment by veo** [comment]
update your go version maybe fix

**Comment by 4riful** [comment]
i have latest go version installled 
![image](https://user-images.githubusercontent.com/45453772/175292781-d640ebe9-70ac-477e-9930-c95717ce7b04.png)
i just upgrade mysystem

**Comment by veo** [comment]
go version must > 1.16
1.17 is better

**Comment by veo** [comment]
you can see https://github.com/veo/vscan/blob/main/static/running.md,some example
