### ISSUE TITLE
指纹探测

### ISSUE THREAD

**Issue by sec1dale** [veo/vscan#3]
指纹探测这个可以调用下棱洞的指纹探测工具应该会更好吧

**Comment by veo** [comment]
> 指纹探测这个可以调用下棱洞的指纹探测工具应该会更好吧

感谢提交issues

首先回答你的问题，很多指纹识别扫描器采用了图标进行判定cms，而vscan是采用首页、200、403、404页面进行综合判断，目前还没有采用图标判断功能，逻辑不同不能直接导入部分公开指纹数据

个人时间有限，如果有丰富内容的想法，欢迎大家pull requests，任何提交我都会积极检查并更新
