### ISSUE TITLE
windows上不能运行，即使管理员权限，开启的cmd

### ISSUE THREAD

**Issue by komomon** [veo/vscan#35]
windows上不能运行，即使管理员权限，开启的cmd
![image](https://user-images.githubusercontent.com/52700174/189336478-8f5a73ef-1e93-425a-86c2-d3e0f7c37ad4.png)

**Comment by veo** [comment]
感谢提交issues

你的-top-ports 值输入错了，只能是 100 1000 full http其中的一种，这里建议不用加-top-ports参数，也会扫http常用端口

**Comment by komomon** [comment]
> 感谢提交issues
> 
> 你的-top-ports 值输入错了，只能是 100 1000 full http其中的一种，这里建议不用加-top-ports参数，也会扫http常用端口

我修改了为100，但是依然不行，另外linux上指定-top-ports，使用-o不会输出结果吗，实测没有输出，而且即使有web好像没有指纹识别，目录扫描等
![image](https://user-images.githubusercontent.com/52700174/189340769-ae814687-70d4-4616-b3e2-69a7d866fa5b.png)

**Comment by veo** [comment]
使用方法可参考
https://github.com/veo/vscan/blob/main/static/running.md

单一链接可直接输入链接进行扫描

**Comment by komomon** [comment]
参看了，发现个bug，输出的结果只会存储扫描到的web的内容，不会存储扫描到的其他端口等信息

**Comment by veo** [comment]
> 参看了，发现个bug，输出的结果只会存储扫描到的web的内容，不会存储扫描到的其他端口等信息

会吧？port.name.csv？
