### ISSUE TITLE
关于结果保存

### ISSUE THREAD

**Issue by r00tSe7en** [veo/vscan#4]
在保存漏洞、httpx指纹检测结果之外，可不可以支持单独保存
naabu的结果到一个文件
```
ip:port
ip:port
```
httpx的结果到一个文件
```
http://ip:port
https://ip:port
```
后续方便调nuclei进行扫描

**Comment by veo** [comment]
感谢提交issue，后续版本会考虑加上导出适配nuclei的参数

**Comment by veo** [comment]
v2.0.1已支持各类文件导出
