### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wuguang9** [veo/vscan#41]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x679e58]

**Comment by veo** [comment]
有多一点的保存信息吗？方便定位

**Comment by wuguang9** [comment]
> 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x679e58]

goroutine 37266429 [running]:
net/url.(*URL).ResolveReference(0xc0041681b0, 0x0)
	/opt/hostedtoolcache/go/1.17.11/x64/src/net/url/url.go:1095 +0x38
github.com/veo/vscan/brute.getinput({0xc00266acf0, 0x0})
	/home/runner/work/vscan/vscan/brute/admin_brute.go:34 +0x19b
github.com/veo/vscan/brute.Admin_brute({0xc00266acf0, 0x2})
	/home/runner/work/vscan/vscan/brute/admin_brute.go:79 +0x45
github.com/veo/vscan/pocs_go.POCcheck({0xc0021c2040, 0x3, 0x4}, {0xc00417d7a0, 0x17}, {0xc00266acf0, 0x13}, 0x0)
	/home/runner/work/vscan/vscan/pocs_go/go_poc_check.go:162 +0x278c
github.com/veo/vscan/pkg/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc000aa0fe0, 0x10}, ...)
	/home/runner/work/vscan/vscan/pkg/httpx/runner/runner.go:1295 +0x5959
github.com/veo/vscan/pkg/httpx/runner.(*Runner).process.func1({0xc000aa0fe0, 0x10}, {0x15a2d55, 0x3}, {0x15c1811, 0xa})
	/home/runner/work/vscan/vscan/pkg/httpx/runner/runner.go:694 +0x125
created by github.com/veo/vscan/pkg/httpx/runner.(*Runner).process
	/home/runner/work/vscan/vscan/pkg/httpx/runner/runner.go:692 +0x965
