### ISSUE TITLE
vscan 扫描tomcat 默认口令不扫不出来后，更改了用户名密码。

### ISSUE THREAD

**Issue by york-cmd** [veo/vscan#46]
1.搭建了vulhub tomcat弱口令靶场
正常使用tomcat:tomcat可以登录
2.使用vscan不能扫出漏洞，扫完以后默认口令不能登陆了。

**Comment by veo** [comment]
tomcat 7以后有错误次数登陆限制，好像是五个，所以其实只能爆破五次，可以尝试优化字典自行编译

**Comment by york-cmd** [comment]
困惑了好久 ，感谢大佬。
