### ISSUE TITLE
关于多目标扫描

### ISSUE THREAD

**Issue by dopenser** [veo/vscan#6]
一次扫描大于一定数量在webscan步骤会报错
<img width="916" alt="image" src="https://user-images.githubusercontent.com/57133031/159198430-217f698b-5d68-4556-aa1a-e38c6b709110.png">

**Comment by veo** [comment]
> 一次扫描大于一定数量在webscan步骤会报错 <img alt="image" width="916" src="https://user-images.githubusercontent.com/57133031/159198430-217f698b-5d68-4556-aa1a-e38c6b709110.png">

感谢提交issue，提交了很有意义的问题。

我仔细的审查了代码，确实找到了问题出现的原因。（详解：https://blog.csdn.net/HYZX_9987/article/details/121932735）

但是我现在不敢随意加锁修改代码，这需要严谨的逻辑和大量的测试。问题先进行搁置处理

**Comment by veo** [comment]
临时性修复方案，添加了延迟处理

**Comment by veo** [comment]
v2.0.1已彻底修复此BUG
