### ISSUE TITLE
centos linux 使用出错

### ISSUE THREAD

**Issue by gcxtx01** [veo/vscan#7]
![image](https://user-images.githubusercontent.com/82226301/162670416-164ea3d0-771c-4574-826b-547159c2ec2a.png)

**Comment by veo** [comment]
> ![image](https://user-images.githubusercontent.com/82226301/162670416-164ea3d0-771c-4574-826b-547159c2ec2a.png)

感谢您提交issue

是编译动态库版本不一样产生的问题，两种临时解决方案

1.可以建个软链接/lib64/libpcap.so.0.8到目前版本的libpcap.so
2.可以下载源码后自行编译

以后我会完善一下编译设置彻底解决这个问题
