### ISSUE TITLE
您好，使用-json参数无输出

### ISSUE THREAD

**Issue by 15536818056** [veo/vscan#8]
输入如下命令
```
λ vscan.exe -host miyihouse.cn -json xxx.json
```
无xxx.json输出

**Comment by veo** [comment]
> 输入如下命令
> 
> ```
> λ vscan.exe -host miyihouse.cn -json xxx.json
> ```
> 
> 无xxx.json输出

哈哈，这个功能我觉得太麻烦被我阉割了，没想到吧

**Comment by 15536818056** [comment]
嗯嗯确实没想到

**Comment by veo** [comment]
v2.0.1版本已支持json
