### ISSUE TITLE
添加url列表功能

### ISSUE THREAD

**Issue by gcxtx01** [veo/vscan#9]
能不能添加url列表功能，只扫描url列表里的网站，不自行探测服务。

**Comment by veo** [comment]
> 能不能添加url列表功能，只扫描url列表里的网站，不自行探测服务。

感谢提交issues
其实现在也能扫url，但是可能没那么好用，有些小问题，记下来了后续我会改进改进

**Comment by veo** [comment]
v2.0.1已支持只扫描url列表
